import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  setLanguage: (language: Language) => void;
  language: Language;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'auth.sendCode': 'Send 4-Digit Code',
    'auth.enterCode': 'Enter 4-Digit Verification Code',
    'auth.testCode': 'For testing: Use code 1234',
    'auth.phoneNumber': 'Mobile Number',
    'auth.enterPhone': 'Enter your mobile number to get started',
    'auth.verifyNumber': 'Verify Your Number',
    'auth.codeSentTo': 'We\'ve sent a 4-digit code to',
    'auth.resendCode': 'Resend verification code',
    'auth.verifyCode': 'Verify Code',
    'auth.completeProfile': 'Complete Your Profile',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.welcomeBonus': 'You\'ll receive 50 points as a welcome gift!',
    'auth.invalidCode': 'Invalid verification code. Please try again.',
    'auth.verificationFailed': 'Verification failed. Please try again.',
    'auth.sending': 'Sending...',
    'auth.verifying': 'Verifying...',
    'auth.creatingAccount': 'Creating Account...',
    'auth.completeRegistration': 'Complete Registration',
    'auth.welcomeBonusTitle': 'Welcome bonus!',
    'auth.tellUsAboutYou': 'Tell us a bit about yourself to get started',
    'auth.enterFirstName': 'Enter your first name',
    'auth.enterLastName': 'Enter your last name',
    'auth.resendIn': 'Resend code in',
    'auth.welcomeToTaoo': 'Welcome to DO Shopping',
    // Header
    'header.search': 'Search stores and products',
    
    // Navigation
    'nav.home': 'Home',
    'nav.stores': 'Stores',
    'nav.deals': 'Deals',
    'nav.wallet': 'Wallet',
    'nav.account': 'Account',
    'nav.convert': 'Convert',
    
    // Home Page
    'home.promotions': 'Promotions',
    'home.partnerStores': 'Partner Stores',
    'home.earnPoints': 'Earn Points on Every Purchase!',
    'home.earnPointsDesc': 'Shop from partner stores and get rewarded.',
    'home.giftCards': 'Gift Cards',
    'home.premiumOffers': 'Premium Offers',
    'home.geantSelection': 'Géant Selection',
    'home.promotion': 'Promotion',
    'home.fashionSale': 'Fashion Sale',
    'home.summerSale': 'Summer Sale',
    'home.upTo50': 'Up to 50% off',
    'home.upTo70': 'Up to 70% off',
    'home.parisTrip': '4-day trip to Istambul',
    
    // Account Page
    'account.title': 'Account',
    'account.profile': 'Profile',
    'account.completedAt': 'Completed at ',
    'account.accountAge': 'Account age: ',
    'account.level': 'Level',
    'account.currentLevel': 'Your current level',
    'account.myWallet': 'My Wallet',
    'account.inviteFriends': 'Invite Friends',
    'account.shareAndEarn': 'Share and earn points',
    'account.interests': 'Interests',
    'account.history': 'History',
    'account.allTransactions': 'All your transactions',
    'account.helpSupport': 'Help & Support',
    'account.language': 'Language',
    'account.selectLanguage': 'Select your language',
    'account.deleteAccount': 'Delete my account',
    'account.logout': 'Logout',
    'account.terms': 'Terms of Service',
    'account.darkMode': 'Dark Mode',
    'account.lightMode': 'Light Mode',
    'account.themeSettings': 'Change app appearance',
    'account.phone': 'Phone',
    'days': 'days',
    
    // Language Settings
    'language.title': 'Language Settings',
    'language.english': 'English',
    'language.french': 'Français',
    'language.arabic': 'العربية',
    'language.save': 'Save',
    'language.cancel': 'Cancel',
    
    // Wallet
    'wallet.title': 'My Wallet',
    'wallet.availablePoints': 'Available Points',
    'wallet.earnPointsDesc': '1 SAR = 100 Points • Earn points on every purchase',
    'wallet.estimated': 'estimated at',
    'wallet.readMore': 'read more',
    'wallet.scanOrder': 'Scan & Order',
    'wallet.uploadReceipt': 'Upload Receipt',
    'wallet.flouciPay': 'Flouci Pay',
    'wallet.earned': 'earned',
    'wallet.redeemed': 'redeemed',
    'wallet.monthlyLimit': 'Monthly Limit',
    'wallet.usedThisMonth': 'Used this month',
    'wallet.available': 'Available',
    'wallet.maxSplit': 'Max Split',
    'wallet.quickActions': 'Quick Actions',
    'wallet.earnPoints': 'Earn Points',
    'wallet.redeem': 'Redeem',
    'wallet.history': 'History',
    'wallet.shop': 'Shop',
    'wallet.recentActivity': 'Recent Activity',
    'wallet.viewAll': 'View All',
    'wallet.howToEarn': 'How to Earn More Points',
    'wallet.shopAtStores': '• Shop at partner stores',
    'wallet.referFriends': '• Refer friends',
    'wallet.dailyCheckin': '• Daily check-in',
    'wallet.mobileSubscription': '• Mobile subscription',
    
    // Deals
    'deals.title': 'Deals',
    'deals.doubleDeal': 'Double Deal',
    'deals.doubleDealDesc': 'Premium offer: Double your cashback plus an extra 20% on all purchases!',
    'deals.featured': 'Featured',
    'deals.viewAll': 'View All',
    'deals.buy': 'Buy',
    'deals.soldOut': 'Sold Out',
    'deals.confirmPurchase': 'Confirm Purchase',
    'deals.aboutToPurchase': 'You are about to purchase:',
    'deals.cost': 'Cost',
    'deals.currentPoints': 'Your current points:',
    'deals.offerCost': 'Offer cost:',
    'deals.pointsRemaining': 'Points remaining:',
    'deals.insufficient': 'Insufficient',
    'deals.notEnoughPoints': 'You don\'t have enough points for this offer.',
    'deals.missing': 'You are missing',
    'deals.points': 'points',
    'deals.cancel': 'Cancel',
    'deals.confirm': 'Confirm',
    
    // QR Scanner
    'qr.scanPartner': 'Scan Partner QR Code',
    'qr.scanningPartner': 'Scanning Partner QR Code...',
    'qr.partnerConfirmed': 'Partner Confirmed!',
    'qr.generateOrder': 'Generate My Order QR Code',
    'qr.orderReady': 'Your Order QR Code is Ready!',
    'qr.showToPartner': 'Show this QR code to the partner to create your order',
    'qr.expiresIn': 'Expires in 10 minutes',
    'qr.howItWorks': 'How it works:',
    'qr.step1': '1. Scan the partner\'s QR code at their location',
    'qr.step2': '2. We\'ll generate your unique order QR code',
    'qr.step3': '3. Partner scans your code to create the order',
    'qr.step4': '4. Proceed to checkout and earn points!',
    
    // Stores
    'stores.title': 'Stores',
    'stores.discoverPartners': 'Discover our partners',
    'stores.over500Stores': 'Over 500 partner stores await you',
    'stores.searchStore': 'Search for a store...',
    'stores.fashionAccessories': 'Fashion & Accessories',
    'stores.technology': 'Technology & Electronics',
    'stores.techConstruction': 'Technology & Construction',
    'stores.travel': 'Travel & Transport',
    'stores.sport': 'Sport & Equipment',
    'stores.home': 'Home & Decor',
    'stores.supermarkets': 'Supermarkets & Food',
    'stores.restaurants': 'Restaurants & Gastronomy',
    'stores.health': 'Health & Wellness',
    'stores.education': 'Education & Services',
    'stores.stores': 'Stores',
    'stores.maxCashback': 'Max Cashback',
    'stores.upTo': 'Up to',
    'stores.support': 'Support',
    
    // Levels
    'basic': 'Basic',
    'silver': 'Silver',
    'gold': 'Gold',
    'level.memberSince': 'Member since',
    'level.days': 'days',
    'level.progressTo': 'Progress to',
    'level.maxLevelReached': 'Maximum Level Reached!',
    'level.allBenefitsUnlocked': 'You have unlocked all benefits',
    'level.yourBenefits': 'Your benefits',
    'level.unlockAt': 'Unlock at Level',
    'level.howToEarnMore': 'How to earn more points',
    'level.purchasesAtStores': 'Purchases at partner stores',
    'level.friendReferrals': 'Friend referrals',
    'level.dailyLogin': 'Daily login',
    'level.mobileSubscription': 'Mobile subscription',
    
    // Upgrade Account
    'upgrade.confirmUpgrade': 'Confirm Account Upgrade',
    'upgrade.verifyIdentity': 'Verify Your Identity',
    'upgrade.enter4Digit': 'Enter 4-Digit Verification Code',
    'upgrade.upgradingTo': 'Upgrading to',
    'upgrade.codeSentForUpgrade': '4-digit verification code sent for upgrade',
    'upgrade.confirmUpgradeButton': 'Confirm Upgrade',
    'upgrade.processingUpgrade': 'Processing Upgrade...',
    'upgrade.chooseYourPlan': 'Choose DO Shopping plan',
    'upgrade.free': 'Free',
    'upgrade.cashbackStandard': 'Standard Cashback',
    'upgrade.onlinePayment': 'Online Payment',
    'upgrade.onlinePaymentDesc': 'Online payment with Flouci Wallet',
    'upgrade.mobileSubscription': 'Mobile Subscription',
    'upgrade.pointsPerDay': 'points per day',
    'upgrade.splitPayment': 'Split Payment',
    'upgrade.splitPaymentDesc': 'Up to 6 monthly installments',
    'upgrade.premiumOffersAccess': 'Access to all premium offers',
    'upgrade.extendedMonthlyLimit': 'Extended Monthly Limit',
    'upgrade.extendedLimitDesc': 'Increased monthly purchase limit',
    'upgrade.cashbackExtra': 'Extra Cashback',
    'upgrade.morePercentThanBasic': 'more than Basic',
    'upgrade.doubledReferral': 'Doubled Referral',
    'upgrade.referralPointsDesc': 'points per referred friend',
    'upgrade.maxPoints': 'Maximum Points',
    'upgrade.vipAccess': 'Exclusive VIP Access',
    'upgrade.vipAccessDesc': 'Private sales and exclusive offers',
    'upgrade.premiumMobile': 'Premium Mobile Subscription',
    'upgrade.extendedSplitPayment': 'Extended Split Payment',
    'upgrade.extendedSplitDesc': 'Up to 6 installments + preferential terms',
    'upgrade.cashbackPointsSAR': 'Cashback Points/SAR',
    'upgrade.tryFree': 'Try your new level for 3 days Free then',
    'upgrade.perDay': 'day',
    'upgrade.perWeek': 'week',
    'upgrade.ifNotSatisfied': 'If you are not satisfied,',
    'upgrade.unsubscribeAt': 'unsubscribe at',
    'upgrade.monthly': 'Monthly',
    'upgrade.upgradeNow': 'Upgrade Now',
    'upgrade.codeSentToMobile': 'We\'ve sent a 4-digit verification code to your registered mobile number',
    'upgrade.secureUpgrade': 'Secure Upgrade Process',
    'upgrade.verifyForSecurity': 'For your security, we verify your identity before upgrading your account level.',
    'upgrade.testCodeNote': 'Test code: Use 1234 for testing',
    'upgrade.guaranteeTitle': 'Money Back Guarantee',
    'upgrade.guaranteeText': 'Try your new level for 30 days. If you\'re not satisfied, we\'ll refund you completely.',
    'upgrade.currentLevel': 'Current Level',
    'upgrade.currentPoints': 'Current points',
    'upgrade.choosePeriod': 'Choose your period',
    'upgrade.daily': 'Daily',
    'upgrade.weekly': 'Weekly',
    'upgrade.mostPopular': 'Most Popular',
    'upgrade.levelComparison': 'Level Comparison',
    'upgrade.feature': 'Feature',
    'upgrade.pointsPerTND': 'Points per TND',
    'upgrade.referral': 'Referral',
    'upgrade.dailyCheckin': 'Daily check-in',
    'upgrade.installmentPayment': 'Installment payment',
    'upgrade.premiumOffers': 'Premium offers',
    'upgrade.exclusiveVIPAccess': 'Exclusive VIP access',
    'upgrade.limitedOffers': 'Limited offers',

    // Categories
    'category.apparel': 'Apparel',
    'category.beauty': 'Beauty',
    'category.homeKitchen': 'Home & Kitchen',
    'category.tech': 'Tech',
    'category.travel': 'Travel',
    'category.food': 'Food',
    'category.gaming': 'Gaming',
    'category.health': 'Health',

    // Points Info
    'pointsInfo.estimationText': 'This is an estimate of your current points balance, based on the highest conversion rate. To unlock this reward, you must accumulate the required number of points indicated in the offer details.',
    'pointsInfo.changeNotice': 'Please note that the number of points required to obtain rewards and available gift options are subject to change based on our partnerships or at the sole discretion of DO Shopping.',
    'pointsInfo.notMoney': 'Points are neither money, nor virtual tokens, nor digital currency.',
    'pointsInfo.checkRegularly': 'Feel free to regularly check the Convert page to not miss out on the reward you want, as well as current offers!',
    'pointsInfo.understood': 'Got it!',

    // Common
    'common.back': 'Back',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.loading': 'Loading...',
    'common.success': 'Success',
    'common.points': 'points',
    'common.quantity': 'Quantity',
    'common.new': 'New',
    
    // Convert Page
    'convert.title': 'Convert Points',
    'convert.availablePoints': 'Available Points',
    'convert.pointsDesc': 'Convert your points into exclusive rewards',
    'convert.categories': 'Categories',
    'convert.filter': 'Filter',
    'convert.all': 'All',
    'convert.available': 'Available',
    'convert.upcoming': 'Upcoming',
    'convert.expired': 'Expired',
    'convert.giftCards': 'Gift Cards',
    'convert.freeProducts': 'Free Products',
    'convert.charity': 'Charity',
    'convert.flouciTransfer': 'Flouci Transfer',
    'convert.stays': 'Stays',
    'convert.noItems': 'No items found',
    'convert.noItemsDesc': 'No rewards available for selected filters.',
    'convert.partner': 'Partner',
    'convert.remaining': 'Remaining',
    'convert.availableFrom': 'Available from',
    'convert.expiredOn': 'Expired on',
    'convert.insufficient': 'Insufficient',
    'convert.convert': 'Convert',
    'convert.tips': 'Conversion Tips',
    'convert.tip1': 'Gift cards never expire once purchased',
    'convert.tip2': 'Free products are limited in quantity',
    'convert.tip3': 'Charity donations are tax deductible',
    'convert.tip4': 'Flouci transfers are instant',
    'convert.stats': 'Statistics',
    'convert.total': 'Total',
    'convert.specialOffer': 'Special Offer',
    'convert.distributed': 'Distributed',
    'convert.quantity': 'Quantity',
  },
  
  fr: {
    'auth.sendCode': 'Envoyer le Code à 4 Chiffres',
    'auth.enterCode': 'Entrez le Code de Vérification à 4 Chiffres',
    'auth.testCode': 'Pour les tests : Utilisez le code 1234',
    'auth.phoneNumber': 'Numéro de Mobile',
    'auth.enterPhone': 'Entrez votre numéro de mobile pour commencer',
    'auth.verifyNumber': 'Vérifiez Votre Numéro',
    'auth.codeSentTo': 'Nous avons envoyé un code à 4 chiffres à',
    'auth.resendCode': 'Renvoyer le code de vérification',
    'auth.verifyCode': 'Vérifier le Code',
    'auth.completeProfile': 'Complétez Votre Profil',
    'auth.firstName': 'Prénom',
    'auth.lastName': 'Nom',
    'auth.welcomeBonus': 'Vous recevrez 50 points comme cadeau de bienvenue !',
    'auth.invalidCode': 'Code de vérification invalide. Veuillez réessayer.',
    'auth.verificationFailed': 'Échec de la vérification. Veuillez réessayer.',
    'auth.sending': 'Envoi en cours...',
    'auth.verifying': 'Vérification...',
    'auth.creatingAccount': 'Création du compte...',
    'auth.completeRegistration': 'Terminer l\'inscription',
    'auth.welcomeBonusTitle': 'Bonus de bienvenue !',
    'auth.tellUsAboutYou': 'Parlez-nous un peu de vous pour commencer',
    'auth.enterFirstName': 'Entrez votre prénom',
    'auth.enterLastName': 'Entrez votre nom',
    'auth.resendIn': 'Renvoyer le code dans',
    'auth.welcomeToTaoo': 'Bienvenue chez TAOO',
    // Header
    'header.search': 'Rechercher des magasins et produits',
    
    // Navigation
    'nav.home': 'Accueil',
    'nav.stores': 'Magasins',
    'nav.deals': 'Offres',
    'nav.wallet': 'Portefeuille',
    'nav.account': 'Compte',
    'nav.convert': 'Convertir',
    
    // Home Page
    'home.promotions': 'Promotions',
    'home.partnerStores': 'Magasins Partenaires',
    'home.earnPoints': 'Gagnez des Points à Chaque Achat !',
    'home.earnPointsDesc': 'Achetez chez nos partenaires et soyez récompensé.',
    'home.giftCards': 'Cartes Cadeaux',
    'home.premiumOffers': 'Offres Premium',
    'home.geantSelection': 'Sélection Géant',
    'home.promotion': 'Promotion',
    'home.fashionSale': 'Soldes Mode',
    'home.summerSale': 'Soldes d\'Été',
    'home.upTo50': 'Jusqu\'à 50% de réduction',
    'home.upTo70': 'Jusqu\'à 70% de réduction',
    'home.parisTrip': 'Voyage de 4 jours à Istanbul',
    
    // Account Page
    'account.title': 'Compte',
    'account.profile': 'Profil',
    'account.completedAt': 'Complété à ',
    'account.accountAge': 'Âge du compte : ',
    'account.level': 'Niveau',
    'account.currentLevel': 'Votre niveau actuel',
    'account.myWallet': 'Mon Portefeuille',
    'account.inviteFriends': 'Inviter des Amis',
    'account.shareAndEarn': 'Partagez et gagnez des points',
    'account.interests': 'Centres d\'Intérêt',
    'account.history': 'Historique',
    'account.allTransactions': 'Toutes vos transactions',
    'account.helpSupport': 'Aide et Contact',
    'account.language': 'Langue',
    'account.selectLanguage': 'Sélectionnez votre langue',
    'account.deleteAccount': 'Supprimer mon compte',
    'account.logout': 'Se déconnecter',
    'account.terms': 'Conditions Générales d\'Utilisation',
    'account.darkMode': 'Mode Sombre',
    'account.lightMode': 'Mode Clair',
    'account.themeSettings': 'Changer l\'apparence de l\'application',
    'account.phone': 'Téléphone',
    'days': 'jours',
    
    // Language Settings
    'language.title': 'Paramètres de Langue',
    'language.english': 'English',
    'language.french': 'Français',
    'language.arabic': 'العربية',
    'language.save': 'Sauvegarder',
    'language.cancel': 'Annuler',
    
    // Wallet
    'wallet.title': 'Mon Portefeuille',
    'wallet.availablePoints': 'Points Disponibles',
    'wallet.earnPointsDesc': '1 SAR = 100 Points • Gagnez des points à chaque achat',
    'wallet.estimated': 'estimé à',
    'wallet.readMore': 'lire la suite',
    'wallet.scanOrder': 'Scanner et Commander',
    'wallet.uploadReceipt': 'Télécharger Reçu',
    'wallet.flouciPay': 'Paiement Flouci',
    'wallet.earned': 'gagné',
    'wallet.redeemed': 'échangé',
    'wallet.monthlyLimit': 'Limite Mensuelle',
    'wallet.usedThisMonth': 'Utilisé ce mois',
    'wallet.available': 'Disponible',
    'wallet.maxSplit': 'Fractionnement Max',
    'wallet.quickActions': 'Actions Rapides',
    'wallet.earnPoints': 'Gagner des Points',
    'wallet.redeem': 'Échanger',
    'wallet.history': 'Historique',
    'wallet.shop': 'Acheter',
    'wallet.recentActivity': 'Activité Récente',
    'wallet.viewAll': 'Tout Voir',
    'wallet.howToEarn': 'Comment Gagner Plus de Points',
    'wallet.shopAtStores': '• Acheter chez nos partenaires',
    'wallet.referFriends': '• Parrainer des amis',
    'wallet.dailyCheckin': '• Connexion quotidienne',
    'wallet.mobileSubscription': '• Abonnement mobile',
    
    // Deals
    'deals.title': 'Offres',
    'deals.doubleDeal': 'Double Deal',
    'deals.doubleDealDesc': 'Offre premium : doublez votre cashback et bénéficiez de 20% supplémentaires sur tous vos achats.',
    'deals.featured': 'À la Une',
    'deals.viewAll': 'Tout Voir',
    'deals.buy': 'Acheter',
    'deals.soldOut': 'Épuisé',
    'deals.confirmPurchase': 'Confirmer l\'Achat',
    'deals.aboutToPurchase': 'Vous êtes sur le point d\'acheter :',
    'deals.cost': 'Coût',
    'deals.currentPoints': 'Vos points actuels :',
    'deals.offerCost': 'Coût de l\'offre :',
    'deals.pointsRemaining': 'Points restants :',
    'deals.insufficient': 'Insuffisant',
    'deals.notEnoughPoints': 'Vous n\'avez pas assez de points pour cette offre.',
    'deals.missing': 'Il vous manque',
    'deals.points': 'points',
    'deals.cancel': 'Annuler',
    'deals.confirm': 'Confirmer',
    
    // QR Scanner
    'qr.scanPartner': 'Scanner le QR Code Partenaire',
    'qr.scanningPartner': 'Scan du QR Code Partenaire...',
    'qr.partnerConfirmed': 'Partenaire Confirmé !',
    'qr.generateOrder': 'Générer Mon QR Code de Commande',
    'qr.orderReady': 'Votre QR Code de Commande est Prêt !',
    'qr.showToPartner': 'Montrez ce QR code au partenaire pour créer votre commande',
    'qr.expiresIn': 'Expire dans 10 minutes',
    'qr.howItWorks': 'Comment ça marche :',
    'qr.step1': '1. Scannez le QR code du partenaire à leur emplacement',
    'qr.step2': '2. Nous générerons votre QR code de commande unique',
    'qr.step3': '3. Le partenaire scanne votre code pour créer la commande',
    'qr.step4': '4. Procédez au checkout et gagnez des points !',
    
    // Stores
    'stores.title': 'Magasins',
    'stores.discoverPartners': 'Découvrez nos partenaires',
    'stores.over500Stores': 'Plus de 500 magasins partenaires vous attendent',
    'stores.searchStore': 'Rechercher un magasin...',
    'stores.fashionAccessories': 'Mode & Accessoires',
    'stores.technology': 'Technologie & Électronique',
    'stores.techConstruction': 'Technologie & Construction',
    'stores.travel': 'Voyage & Transport',
    'stores.sport': 'Sport & Équipement',
    'stores.home': 'Maison & Déco',
    'stores.supermarkets': 'Supermarchés & Alimentation',
    'stores.restaurants': 'Restaurants & Gastronomie',
    'stores.health': 'Santé & Bien-être',
    'stores.education': 'Éducation & Services',
    'stores.stores': 'Magasins',
    'stores.maxCashback': 'Cashback Max',
    'stores.upTo': 'Jusqu\'\u00e0',
    'stores.support': 'Support',
    
    // Levels
    'basic': 'Basic',
    'silver': 'Silver',
    'gold': 'Gold',
    'level.memberSince': 'Membre depuis',
    'level.days': 'jours',
    'level.progressTo': 'Progression vers',
    'level.maxLevelReached': 'Niveau Maximum Atteint !',
    'level.allBenefitsUnlocked': 'Vous avez débloqué tous les avantages',
    'level.yourBenefits': 'Vos avantages',
    'level.unlockAt': 'Débloquez au Niveau',
    'level.howToEarnMore': 'Comment gagner plus de points',
    'level.purchasesAtStores': 'Achats chez nos partenaires',
    'level.friendReferrals': 'Parrainage d\'amis',
    'level.dailyLogin': 'Connexion quotidienne',
    'level.mobileSubscription': 'Abonnement mobile',
    
    // Upgrade Account
    'upgrade.confirmUpgrade': 'Confirmer la Mise à Niveau du Compte',
    'upgrade.verifyIdentity': 'Vérifiez Votre Identité',
    'upgrade.enter4Digit': 'Entrez le Code de Vérification à 4 Chiffres',
    'upgrade.upgradingTo': 'Mise à niveau vers',
    'upgrade.codeSentForUpgrade': 'Code de vérification à 4 chiffres envoyé pour la mise à niveau',
    'upgrade.confirmUpgradeButton': 'Confirmer la Mise à Niveau',
    'upgrade.processingUpgrade': 'Traitement de la Mise à Niveau...',
    'upgrade.chooseYourPlan': 'Choisissez votre plan TAOO',
    'upgrade.monthly': 'Mensuel',
    'upgrade.upgradeNow': 'Mettre à Niveau Maintenant',
    'upgrade.codeSentToMobile': 'Nous avons envoyé un code de vérification à 4 chiffres à votre numéro de mobile enregistré',
    'upgrade.secureUpgrade': 'Processus de Mise à Niveau Sécurisé',
    'upgrade.verifyForSecurity': 'Pour votre sécurité, nous vérifions votre identité avant de mettre à niveau votre compte.',
    'upgrade.testCodeNote': 'Code de test : Utilisez 1234 pour les tests',
    'upgrade.guaranteeTitle': 'Garantie Satisfait ou Remboursé',
    'upgrade.guaranteeText': 'Essayez votre nouveau niveau pendant 30 jours. Si vous n\'êtes pas satisfait, nous vous remboursons intégralement.',
    'upgrade.currentLevel': 'Niveau Actuel',
    'upgrade.currentPoints': 'Points actuels',
    'upgrade.choosePeriod': 'Choisissez votre période',
    'upgrade.daily': 'Quotidien',
    'upgrade.weekly': 'Hebdomadaire',
    'upgrade.mostPopular': 'Le plus populaire',
    'upgrade.levelComparison': 'Comparaison des niveaux',
    'upgrade.feature': 'Fonctionnalité',
    'upgrade.pointsPerTND': 'Points par TND',
    'upgrade.referral': 'Parrainage',
    'upgrade.dailyCheckin': 'Connexion quotidienne',
    'upgrade.installmentPayment': 'Paiement fractionné',
    'upgrade.premiumOffers': 'Offres premium',
    'upgrade.exclusiveVIPAccess': 'Accès VIP exclusif',
    'upgrade.free': 'Gratuit',
    'upgrade.cashbackStandard': 'Cashback Standard',
    'upgrade.onlinePayment': 'Paiement en ligne',
    'upgrade.onlinePaymentDesc': 'Paiement en ligne avec Wallet Flouci',
    'upgrade.mobileSubscription': 'Abonnement mobile',
    'upgrade.pointsPerDay': 'points par jour',
    'upgrade.splitPayment': 'Paiement fractionné',
    'upgrade.splitPaymentDesc': 'Jusqu\'à 6 mensualités sans frais',
    'upgrade.premiumOffersAccess': 'Accès à toutes les offres premium',
    'upgrade.extendedMonthlyLimit': 'Limite Mensuelle Étendue',
    'upgrade.extendedLimitDesc': 'Limite d\'achat mensuelle augmentée',
    'upgrade.cashbackExtra': 'Cashback Supplémentaire',
    'upgrade.morePercentThanBasic': 'de plus qu\'avec Basic',
    'upgrade.doubledReferral': 'Parrainage Doublé',
    'upgrade.referralPointsDesc': 'points par ami parrainé',
    'upgrade.maxPoints': 'Points Maximum',
    'upgrade.vipAccess': 'Accès VIP Exclusif',
    'upgrade.vipAccessDesc': 'Ventes privées et offres exclusives',
    'upgrade.premiumMobile': 'Abonnement Mobile Premium',
    'upgrade.extendedSplitPayment': 'Paiement Fractionné Étendu',
    'upgrade.extendedSplitDesc': 'Jusqu\'à 6 mensualités + conditions préférentielles',
    'upgrade.cashbackPointsSAR': 'Points Cashback/SAR',
    'upgrade.tryFree': 'Essayez votre nouveau niveau pendant 3 jours Gratuits puis',
    'upgrade.perDay': 'jour',
    'upgrade.perWeek': 'semaine',
    'upgrade.ifNotSatisfied': 'Si vous n\'êtes pas satisfait,',
    'upgrade.unsubscribeAt': 'désabonnez-vous sur',

    // Categories
    'category.apparel': 'Vêtements',
    'category.beauty': 'Beauté',
    'category.homeKitchen': 'Maison & Cuisine',
    'category.tech': 'Technologie',
    'category.travel': 'Voyage',
    'category.food': 'Nourriture',
    'category.gaming': 'Jeux',
    'category.health': 'Santé',

    // Points Info
    'pointsInfo.estimationText': 'Ceci est une estimation de votre cagnotte actuelle de points, basée sur le taux de conversion le plus élevé. Pour débloquer cette récompense, vous devez accumuler le nombre requis de points indiqué dans les détails de l\'offre.',
    'pointsInfo.changeNotice': 'Veuillez noter que le nombre de points nécessaires pour obtenir des récompenses et les options de cadeaux disponibles sont susceptibles de changer en fonction de nos partenariats ou à la seule discrétion de DO Shopping.',
    'pointsInfo.notMoney': 'Les points ne sont ni de l\'argent, ni des jetons virtuels, ni une monnaie numérique.',
    'pointsInfo.checkRegularly': 'N\'hésitez pas à consulter régulièrement la page Convertir pour ne pas passer à côté de la récompense que vous souhaitez, ainsi que les offres du moment !',
    'pointsInfo.understood': 'C\'est compris !',

    // Common
    'common.back': 'Retour',
    'common.save': 'Sauvegarder',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.loading': 'Chargement...',
    'common.success': 'Succès',
    'common.points': 'points',
    'common.quantity': 'Quantité',
    'common.new': 'Nouveau',
    
    // Convert Page
    'convert.title': 'Convertir mes Points',
    'convert.availablePoints': 'Points Disponibles',
    'convert.pointsDesc': 'Convertissez vos points en récompenses exclusives',
    'convert.categories': 'Catégories',
    'convert.filter': 'Filtrer',
    'convert.all': 'Tout',
    'convert.available': 'Disponible',
    'convert.upcoming': 'À venir',
    'convert.expired': 'Expiré',
    'convert.giftCards': 'Cartes Cadeaux',
    'convert.freeProducts': 'Produits Gratuits',
    'convert.charity': 'Charité',
    'convert.flouciTransfer': 'Transfert Flouci',
    'convert.stays': 'Séjours',
    'convert.noItems': 'Aucun élément trouvé',
    'convert.noItemsDesc': 'Aucune récompense disponible pour les filtres sélectionnés.',
    'convert.partner': 'Partenaire',
    'convert.remaining': 'Restant',
    'convert.availableFrom': 'Disponible à partir du',
    'convert.expiredOn': 'Expiré le',
    'convert.insufficient': 'Insuffisant',
    'convert.convert': 'Convertir',
    'convert.tips': 'Conseils de Conversion',
    'convert.tip1': 'Les cartes cadeaux n\'expirent jamais une fois achetées',
    'convert.tip2': 'Les produits gratuits sont limités en quantité',
    'convert.tip3': 'Les dons de charité sont déductibles fiscalement',
    'convert.tip4': 'Les transferts Flouci sont instantanés',
    'convert.stats': 'Statistiques',
    'convert.total': 'Total',
    'convert.specialOffer': 'Offre Spéciale',
    'convert.distributed': 'Distribué',
    'convert.quantity': 'Quantité',
  },
  
  ar: {
    'auth.sendCode': 'إرسال رمز من 4 أرقام',
    'auth.enterCode': 'أدخل رمز التحقق المكون من 4 أرقام',
    'auth.testCode': 'للاختبار: استخدم الرمز 1234',
    'auth.phoneNumber': 'رقم الهاتف المحمول',
    'auth.enterPhone': 'أدخل رقم هاتفك المحمول للبدء',
    'auth.verifyNumber': 'تحقق من رقمك',
    'auth.codeSentTo': 'لقد أرسلنا رمزاً مكوناً من 4 أرقام إلى',
    'auth.resendCode': 'إعادة إرسال رمز التحقق',
    'auth.verifyCode': 'تحقق من الرمز',
    'auth.completeProfile': 'أكمل ملفك الشخصي',
    'auth.firstName': 'الاسم الأول',
    'auth.lastName': 'اسم العائلة',
    'auth.welcomeBonus': 'ستحصل على 50 نقطة كهدية ترحيب!',
    'auth.invalidCode': 'رمز التحقق غير صحيح. يرجى المحاولة مرة أخرى.',
    'auth.verificationFailed': 'فشل التحقق. يرجى المحاولة مرة أخرى.',
    'auth.sending': 'جاري الإرسال...',
    'auth.verifying': 'جاري التحقق...',
    'auth.creatingAccount': 'جاري إنشاء الحساب...',
    'auth.completeRegistration': 'إكمال التسجيل',
    'auth.welcomeBonusTitle': 'مكافأة الترحيب!',
    'auth.tellUsAboutYou': 'أخبرنا قليلاً عن نفسك للبدء',
    'auth.enterFirstName': 'أدخل اسمك الأول',
    'auth.enterLastName': 'أدخل اسم عائلتك',
    'auth.resendIn': 'إعادة إرسال الرمز خلال',
    'auth.welcomeToTaoo': 'مرحباً بك في TAOO',
    // Header
    'header.search': 'البحث عن المتاجر والمنتجات',
    
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.stores': 'المتاجر',
    'nav.deals': 'العروض',
    'nav.wallet': 'المحفظة',
    'nav.account': 'الحساب',
    'nav.convert': 'تحويل',
    
    // Home Page
    'home.promotions': 'العروض الترويجية',
    'home.partnerStores': 'المتاجر الشريكة',
    'home.earnPoints': 'اكسب نقاط مع كل عملية شراء!',
    'home.earnPointsDesc': 'تسوق من المتاجر الشريكة واحصل على المكافآت.',
    'home.giftCards': 'بطاقات الهدايا',
    'home.premiumOffers': 'العروض المميزة',
    'home.geantSelection': 'مجموعة جيان',
    'home.promotion': 'عرض ترويجي',
    'home.fashionSale': 'تخفيضات الأزياء',
    'home.summerSale': 'تخفيضات الصيف',
    'home.upTo50': 'خصم يصل إلى 50%',
    'home.upTo70': 'خصم يصل إلى 70%',
    'home.parisTrip': 'رحلة 4 أيام إلى باريس',
    
    // Account Page
    'account.title': 'الحساب',
    'account.profile': 'الملف الشخصي',
    'account.completedAt': 'مكتمل بنسبة ',
    'account.accountAge': 'عمر الحساب: ',
    'account.level': 'المستوى',
    'account.currentLevel': 'مستواك الحالي',
    'account.myWallet': 'محفظتي',
    'account.inviteFriends': 'دعوة الأصدقاء',
    'account.shareAndEarn': 'شارك واكسب النقاط',
    'account.interests': 'الاهتمامات',
    'account.history': 'السجل',
    'account.allTransactions': 'جميع معاملاتك',
    'account.helpSupport': 'المساعدة والدعم',
    'account.language': 'اللغة',
    'account.selectLanguage': 'اختر لغتك',
    'account.deleteAccount': 'حذف حسابي',
    'account.logout': 'تسجيل الخروج',
    'account.terms': 'شروط الخدمة',
    'account.darkMode': 'الوضع المظلم',
    'account.lightMode': 'الوضع الفاتح',
    'account.themeSettings': 'تغيير مظهر التطبيق',
    'account.phone': 'الهاتف',
    'days': 'أيام',
    
    // Language Settings
    'language.title': 'إعدادات اللغة',
    'language.english': 'English',
    'language.french': 'Français',
    'language.arabic': 'العربية',
    'language.save': 'حفظ',
    'language.cancel': 'إلغاء',
    
    // Wallet
    'wallet.title': 'محفظتي',
    'wallet.availablePoints': 'النقاط المتاحة',
    'wallet.earnPointsDesc': '1 ريال = 100 نقطة • اكسب نقاط مع كل عملية شراء',
    'wallet.estimated': 'تقدير بـ',
    'wallet.readMore': 'اقرأ المزيد',
    'wallet.scanOrder': 'مسح وطلب',
    'wallet.uploadReceipt': 'تحميل الإيصال',
    'wallet.flouciPay': 'دفع فلوسي',
    'wallet.earned': 'مكتسب',
    'wallet.redeemed': 'مستبدل',
    'wallet.monthlyLimit': 'الحد الشهري',
    'wallet.usedThisMonth': 'المستخدم هذا الشهر',
    'wallet.available': 'متاح',
    'wallet.maxSplit': 'أقصى تقسيط',
    'wallet.quickActions': 'الإجراءات السريعة',
    'wallet.earnPoints': 'كسب النقاط',
    'wallet.redeem': 'استبدال',
    'wallet.history': 'السجل',
    'wallet.shop': 'تسوق',
    'wallet.recentActivity': 'النشاط الأخير',
    'wallet.viewAll': 'عرض الكل',
    'wallet.howToEarn': 'كيفية كسب المزيد من النقاط',
    'wallet.shopAtStores': '• التسوق من المتاجر الشريكة',
    'wallet.referFriends': '• إحالة الأصدقاء',
    'wallet.dailyCheckin': '• تسجيل الدخول اليومي',
    'wallet.mobileSubscription': '• الاشتراك المحمول',
    
    // Deals
    'deals.title': 'العروض',
    'deals.doubleDeal': 'العرض المضاعف',
    'deals.doubleDealDesc': 'عرض مميز: ضعف ضاعف استردادك النقدي!  20% إضافية على جميع المشتريات',
    'deals.featured': 'مميز',
    'deals.viewAll': 'عرض الكل',
    'deals.buy': 'شراء',
    'deals.soldOut': 'نفد المخزون',
    'deals.confirmPurchase': 'تأكيد الشراء',
    'deals.aboutToPurchase': 'أنت على وشك شراء:',
    'deals.cost': 'التكلفة',
    'deals.currentPoints': 'نقاطك الحالية:',
    'deals.offerCost': 'تكلفة العرض:',
    'deals.pointsRemaining': 'النقاط المتبقية:',
    'deals.insufficient': 'غير كافي',
    'deals.notEnoughPoints': 'ليس لديك نقاط كافية لهذا العرض.',
    'deals.missing': 'ينقصك',
    'deals.points': 'نقطة',
    'deals.cancel': 'إلغاء',
    'deals.confirm': 'تأكيد',
    
    // QR Scanner
    'qr.scanPartner': 'مسح رمز QR الخاص بالشريك',
    'qr.scanningPartner': 'مسح رمز QR الخاص بالشريك...',
    'qr.partnerConfirmed': 'تم تأكيد الشريك!',
    'qr.generateOrder': 'إنشاء رمز QR الخاص بطلبي',
    'qr.orderReady': 'رمز QR الخاص بطلبك جاهز!',
    'qr.showToPartner': 'اعرض هذا الرمز على الشريك لإنشاء طلبك',
    'qr.expiresIn': 'ينتهي خلال 10 دقائق',
    'qr.howItWorks': 'كيف يعمل:',
    'qr.step1': '1. امسح رمز QR الخاص بالشريك في موقعهم',
    'qr.step2': '2. سننشئ رمز QR الفريد الخاص بطلبك',
    'qr.step3': '3. يمسح الشريك رمزك لإنشاء الطلب',
    'qr.step4': '4. تابع إلى الدفع واكسب النقاط!',
    
    // Stores
    'stores.title': 'المتاجر',
    'stores.discoverPartners': 'اكتشف شركاءنا',
    'stores.over500Stores': 'أكثر من 500 متجر شريك في انتظارك',
    'stores.searchStore': 'البحث عن متجر...',
    'stores.fashionAccessories': 'الأزياء والإكسسوارات',
    'stores.technology': 'التكنولوجيا والإلكترونيات',
    'stores.techConstruction': 'التكنولوجيا والبناء',
    'stores.travel': 'السفر والنقل',
    'stores.sport': 'الرياضة والمعدات',
    'stores.home': 'المنزل والديكور',
    'stores.supermarkets': 'السوبر ماركت والطعام',
    'stores.restaurants': 'المطاعم والطعام',
    'stores.health': 'الصحة والعافية',
    'stores.education': 'التعليم والخدمات',
    'stores.stores': 'متاجر',
    'stores.maxCashback': 'أقصى استرداد نقدي',
    'stores.upTo': 'حتى',
    'stores.support': 'الدعم',
    
    // Levels
    'basic': 'الأساسي',
    'silver': 'الفضي',
    'gold': 'الذهبي',
    'level.memberSince': 'عضو منذ',
    'level.days': 'يوم',
    'level.progressTo': 'التقدم إلى',
    'level.maxLevelReached': 'تم الوصول للمستوى الأقصى!',
    'level.allBenefitsUnlocked': 'لقد فتحت جميع المزايا',
    'level.yourBenefits': 'مزاياك',
    'level.unlockAt': 'افتح في المستوى',
    'level.howToEarnMore': 'كيفية كسب المزيد من النقاط',
    'level.purchasesAtStores': 'المشتريات من المتاجر الشريكة',
    'level.friendReferrals': 'إحالة الأصدقاء',
    'level.dailyLogin': 'تسجيل الدخول اليومي',
    'level.mobileSubscription': 'الاشتراك المحمول',
    
    // Upgrade Account
    'upgrade.confirmUpgrade': 'تأكيد ترقية الحساب',
    'upgrade.verifyIdentity': 'تحقق من هويتك',
    'upgrade.enter4Digit': 'أدخل رمز التحقق المكون من 4 أرقام',
    'upgrade.upgradingTo': 'الترقية إلى',
    'upgrade.codeSentForUpgrade': 'تم إرسال رمز التحقق المكون من 4 أرقام للترقية',
    'upgrade.confirmUpgradeButton': 'تأكيد الترقية',
    'upgrade.processingUpgrade': 'معالجة الترقية...',
    'upgrade.chooseYourPlan': 'اختر خطة TAOO الخاصة بك',
    'upgrade.monthly': 'شهري',
    'upgrade.upgradeNow': 'ترقية الآن',
    'upgrade.codeSentToMobile': 'لقد أرسلنا رمز تحقق مكون من 4 أرقام إلى رقم هاتفك المحمول المسجل',
    'upgrade.secureUpgrade': 'عملية ترقية آمنة',
    'upgrade.verifyForSecurity': 'من أجل أمانك، نتحقق من هويتك قبل ترقية مستوى حسابك.',
    'upgrade.testCodeNote': 'رمز الاختبار: استخدم 1234 للاختبار',
    'upgrade.guaranteeTitle': 'ضمان استرداد الأموال',
    'upgrade.guaranteeText': 'جرب مستواك الجديد لمدة 30 يوماً. إذا لم تكن راضياً، سنعيد لك أموالك بالكامل.',
    'upgrade.currentLevel': 'المستوى الحالي',
    'upgrade.currentPoints': 'النقاط الحالية',
    'upgrade.choosePeriod': 'اختر فترتك',
    'upgrade.daily': 'يومي',
    'upgrade.weekly': 'أسبوعي',
    'upgrade.mostPopular': 'الأكثر شعبية',
    'upgrade.levelComparison': 'مقارنة المستويات',
    'upgrade.feature': 'الميزة',
    'upgrade.pointsPerTND': 'نقاط لكل دينار',
    'upgrade.referral': 'الإحالة',
    'upgrade.dailyCheckin': 'تسجيل الدخول اليومي',
    'upgrade.installmentPayment': 'الدفع بالتقسيط',
    'upgrade.premiumOffers': 'العروض المميزة',
    'upgrade.exclusiveVIPAccess': 'الوصول الحصري VIP',
    'upgrade.free': 'مجاني',
    'upgrade.cashbackStandard': 'استرداد نقدي قياسي',
    'upgrade.onlinePayment': 'الدفع عبر الإنترنت',
    'upgrade.onlinePaymentDesc': 'الدفع عبر الإنترنت بواسطة محفظة فلوسي',
    'upgrade.mobileSubscription': 'الاشتراك المحمول',
    'upgrade.pointsPerDay': 'نقطة في اليوم',
    'upgrade.splitPayment': 'الدفع بالتقسيط',
    'upgrade.splitPaymentDesc': 'حتى 6 أقساط شهرية',
    'upgrade.premiumOffersAccess': 'الوصول إلى جميع العروض المميزة',
    'upgrade.extendedMonthlyLimit': 'الحد الشهري الموسع',
    'upgrade.extendedLimitDesc': 'زيادة حد الشراء الشهري',
    'upgrade.cashbackExtra': 'استرداد نقدي إضافي',
    'upgrade.morePercentThanBasic': 'أكثر من الأساسي',
    'upgrade.doubledReferral': 'إحالة مضاعفة',
    'upgrade.referralPointsDesc': 'نقطة لكل صديق محال',
    'upgrade.maxPoints': 'الحد الأقصى من النقاط',
    'upgrade.vipAccess': 'وصول VIP حصري',
    'upgrade.vipAccessDesc': 'مبيعات خاصة وعروض حصرية',
    'upgrade.premiumMobile': 'اشتراك محمول مميز',
    'upgrade.extendedSplitPayment': 'دفع بالتقسيط موسع',
    'upgrade.extendedSplitDesc': 'حتى 6 أقساط + شروط تفضيلية',
    'upgrade.cashbackPointsSAR': 'نقاط الاسترداد النقدي/ريال',
    'upgrade.tryFree': 'جرب مستواك الجديد لمدة 3 أيام مجاناً ثم',
    'upgrade.perDay': 'يوم',
    'upgrade.perWeek': 'أسبوع',
    'upgrade.ifNotSatisfied': 'إذا لم تكن راضياً،',
    'upgrade.unsubscribeAt': 'إلغاء الاشتراك على',

    // Categories
    'category.apparel': 'الملابس',
    'category.beauty': 'الجمال',
    'category.homeKitchen': 'المنزل والمطبخ',
    'category.tech': 'التكنولوجيا',
    'category.travel': 'السفر',
    'category.food': 'الطعام',
    'category.gaming': 'الألعاب',
    'category.health': 'الصحة',

    // Points Info
    'pointsInfo.estimationText': 'هذا تقدير لرصيد نقاطك الحالي، بناءً على أعلى معدل تحويل. لفتح هذه المكافأة، يجب عليك تجميع العدد المطلوب من النقاط المشار إليه في تفاصيل العرض.',
    'pointsInfo.changeNotice': 'يرجى ملاحظة أن عدد النقاط المطلوبة للحصول على المكافآت وخيارات الهدايا المتاحة قابلة للتغيير بناءً على شراكاتنا أو وفقًا لتقدير DO Shopping وحده.',
    'pointsInfo.notMoney': 'النقاط ليست نقودًا ولا رموزًا افتراضية ولا عملة رقمية.',
    'pointsInfo.checkRegularly': 'لا تتردد في التحقق بانتظام من صفحة التحويل حتى لا تفوت المكافأة التي تريدها، بالإضافة إلى العروض الحالية!',
    'pointsInfo.understood': 'فهمت!',

    // Common
    'common.back': 'رجوع',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.close': 'إغلاق',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.points': 'نقاط',
    'common.quantity': 'الكمية',
    'common.new': 'جديد',
    
    // Convert Page
    'convert.title': 'تحويل النقاط',
    'convert.availablePoints': 'النقاط المتاحة',
    'convert.pointsDesc': 'حول نقاطك إلى مكافآت حصرية',
    'convert.categories': 'الفئات',
    'convert.filter': 'تصفية',
    'convert.all': 'الكل',
    'convert.available': 'متاح',
    'convert.upcoming': 'قادم',
    'convert.expired': 'منتهي الصلاحية',
    'convert.giftCards': 'بطاقات الهدايا',
    'convert.freeProducts': 'منتجات مجانية',
    'convert.charity': 'الخيرية',
    'convert.flouciTransfer': 'تحويل فلوسي',
    'convert.stays': 'الإقامات',
    'convert.noItems': 'لم يتم العثور على عناصر',
    'convert.noItemsDesc': 'لا توجد مكافآت متاحة للمرشحات المحددة.',
    'convert.partner': 'الشريك',
    'convert.remaining': 'المتبقي',
    'convert.availableFrom': 'متاح من',
    'convert.expiredOn': 'انتهت صلاحيته في',
    'convert.insufficient': 'غير كافي',
    'convert.convert': 'تحويل',
    'convert.tips': 'نصائح التحويل',
    'convert.tip1': 'بطاقات الهدايا لا تنتهي صلاحيتها بمجرد شرائها',
    'convert.tip2': 'المنتجات المجانية محدودة الكمية',
    'convert.tip3': 'التبرعات الخيرية قابلة للخصم الضريبي',
    'convert.tip4': 'تحويلات فلوسي فورية',
    'convert.stats': 'الإحصائيات',
    'convert.total': 'المجموع',
    'convert.specialOffer': 'عرض خاص',
    'convert.distributed': 'موزع',
    'convert.quantity': 'الكمية',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('ar'); // Default to Arabic for Saudi market

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div className={language === 'ar' ? 'rtl' : 'ltr'} dir={language === 'ar' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}