import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';
import { I18nManager } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  setLanguage: (language: Language) => void;
  language: Language;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'auth.sendCode': 'Send 4-Digit Code',
    'auth.enterCode': 'Enter 4-Digit Verification Code',
    'auth.testCode': 'For testing: Use code 1234',
    'auth.phoneNumber': 'Mobile Number',
    'auth.enterPhone': 'Enter your mobile number to get started',
    'auth.verifyNumber': 'Verify Your Number',
    'auth.codeSentTo': "We've sent a 4-digit code to",
    'auth.resendCode': 'Resend verification code',
    'auth.verifyCode': 'Verify Code',
    'auth.completeProfile': 'Complete Your Profile',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.welcomeBonus': "You'll receive 50 points as a welcome gift!",
    'auth.invalidCode': 'Invalid verification code. Please try again.',
    'auth.verificationFailed': 'Verification failed. Please try again.',
    'auth.sending': 'Sending...',
    'auth.verifying': 'Verifying...',
    'auth.creatingAccount': 'Creating Account...',
    'auth.completeRegistration': 'Complete Registration',
    'auth.welcomeBonusTitle': 'Welcome bonus!',
    'auth.tellUsAboutYou': 'Tell us a bit about yourself to get started',
    'auth.enterFirstName': 'Enter your first name',
    'auth.enterLastName': 'Enter your last name',
    'auth.resendIn': 'Resend code in',
    'auth.welcomeToTaoo': 'Welcome to TAOO',
    'header.search': 'Search stores and products',
    'nav.home': 'Home',
    'nav.stores': 'Stores',
    'nav.deals': 'Deals',
    'nav.wallet': 'Wallet',
    'nav.account': 'Account',
    'nav.convert': 'Convert',
    'home.promotions': 'Promotions',
    'home.featuredPartners': 'Featured Partners',
    'home.hotDeals': 'Hot Deals',
    'home.partnerStores': 'Partner Stores',
    'home.earnPoints': 'Earn Points!',
    'home.earnPointsDesc': 'Shop at partner stores and earn points with every purchase',
    'home.giftCards': 'Gift Cards',
    'home.premiumOffers': 'Premium Offers',
    'home.geantSelection': 'Best Selection',
    'home.promotion': 'Special Promotion',
    'home.quantity': 'Quantity',
    'home.giftCardTitle': 'Gift Card',
    'home.giftCardRedeem': 'Redeem {{amount}} Gift Card? This will deduct points from your balance.',
    'home.premiumOfferTitle': 'Premium Offer',
    'home.premiumOfferDesc': '{{title}} - {{points}} points. Would you like to redeem this offer?',
    'home.specialPromotion': 'Special Promotion',
    'home.specialPromoDesc': '{{title}} - Great deal at our partner store!',
    'home.cancel': 'Cancel',
    'home.confirm': 'Confirm',
    'home.success': 'Success',
    'home.giftCardRedeemed': 'Gift card redeemed!',
    'home.viewDetails': 'View Details',
    'home.viewStore': 'View Store',
    'deals.title': 'Deals',
    'deals.upgradeNow': 'Upgrade Now',
    'stores.title': 'Stores',
    'stores.all': 'All',
    'stores.food': 'Food',
    'stores.fashion': 'Fashion',
    'stores.highTech': 'High Tech',
    'stores.education': 'Education',
    'stores.beauty': 'Beauty',
    'stores.health': 'Health',
    'stores.searchPlaceholder': 'Search stores...',
    'stores.noResults': 'No stores found',
    'stores.cashback': 'cashback',
    'wallet.title': 'My Wallet',
    'wallet.availablePoints': 'Available Points',
    'wallet.estimated': 'Estimated',
    'wallet.readMore': 'Read more',
    'wallet.earnPointsDesc': 'Earn points with every purchase at our partner stores!',
    'wallet.monthlyLimit': 'Monthly Spending Limit',
    'wallet.usedThisMonth': 'Used this month',
    'wallet.availableThisMonth': 'Available this month',
    'wallet.splitPayments': 'Split Payments',
    'wallet.splitUpTo': 'Split purchases up to',
    'wallet.months': 'months',
    'wallet.scanOrder': 'Scan Order',
    'wallet.uploadReceipt': 'Upload Receipt',
    'wallet.redeem': 'Redeem',
    'wallet.flouciPay': 'Flouci Pay',
    'wallet.recentActivity': 'Recent Activity',
    'wallet.earnedAt': 'Earned at',
    'wallet.redeemedAt': 'Redeemed at',
    'wallet.howToEarn': 'How to Earn Points?',
    'wallet.shopAtStores': 'Shop at partner stores',
    'wallet.referFriends': 'Refer friends',
    'wallet.dailyCheckIn': 'Daily check-in',
    'wallet.mobileSubscription': 'Mobile subscription',
    'wallet.pointsInfo': 'Points Information',
    'wallet.pointsValue': '1 point = 0.01 SAR',
    'wallet.pointsDesc': 'Points can be used to redeem gift cards, discounts, and special offers at our partner stores.',
    'wallet.quickActions': 'Quick Actions',
    'wallet.available': 'Available',
    'wallet.maxSplit': 'Max Split',
    'wallet.splitNotAvailable': 'Split payment is not available for your current level',
    'upgrade.title': 'Upgrade Your Account',
    'upgrade.subtitle': 'Choose the plan that fits your lifestyle',
    'upgrade.currentPlan': 'Current Plan',
    'upgrade.mostPopular': 'Most Popular',
    'upgrade.basic': 'Basic',
    'upgrade.silver': 'Silver',
    'upgrade.gold': 'Gold',
    'upgrade.free': 'Free',
    'upgrade.month': '/month',
    'upgrade.selectPlan': 'Select Plan',
    'upgrade.currentPlanBtn': 'Current Plan',
    'upgrade.benefits': 'Benefits',
    'upgrade.basicBenefit1': 'Access to basic deals',
    'upgrade.basicBenefit2': 'Earn points on purchases',
    'upgrade.basicBenefit3': 'Standard cashback rate',
    'upgrade.basicBenefit4': 'Daily rewards wheel',
    'upgrade.silverBenefit1': 'All Basic benefits',
    'upgrade.silverBenefit2': 'Access to Premium deals',
    'upgrade.silverBenefit3': '2x points on all purchases',
    'upgrade.silverBenefit4': 'Split payments up to 6 months',
    'upgrade.silverBenefit5': 'Priority customer support',
    'upgrade.silverBenefit6': 'Monthly spending limit: 7,500 SAR',
    'upgrade.goldBenefit1': 'All Silver benefits',
    'upgrade.goldBenefit2': 'Access to VIP exclusive deals',
    'upgrade.goldBenefit3': '3x points on all purchases',
    'upgrade.goldBenefit4': 'Split payments up to 12 months',
    'upgrade.goldBenefit5': 'Dedicated account manager',
    'upgrade.goldBenefit6': 'Monthly spending limit: 15,000 SAR',
    'upgrade.goldBenefit7': 'Early access to new features',
    'upgrade.goldBenefit8': 'Birthday bonus: 500 points',
    'upgrade.compareTitle': 'Compare Plans',
    'upgrade.feature': 'Feature',
    'upgrade.dealsAccess': 'Deals Access',
    'upgrade.pointsMultiplier': 'Points Multiplier',
    'upgrade.splitPayment': 'Split Payment',
    'upgrade.monthlyLimit': 'Monthly Limit',
    'upgrade.support': 'Support',
    'upgrade.basicDeals': 'Basic',
    'upgrade.premiumDeals': 'Premium',
    'upgrade.vipDeals': 'VIP Exclusive',
    'upgrade.standard': 'Standard',
    'upgrade.priority': 'Priority',
    'upgrade.dedicated': 'Dedicated',
    'upgrade.confirmUpgrade': 'Confirm Upgrade',
    'upgrade.confirmMessage': 'Upgrade to {{plan}} plan for {{price}}/month?',
    'upgrade.cancel': 'Cancel',
    'upgrade.confirm': 'Confirm',
    'upgrade.success': 'Success!',
    'upgrade.successMessage': 'Your account has been upgraded to {{plan}}!',
    'upgrade.error': 'Error',
    'upgrade.errorMessage': 'Failed to upgrade account. Please try again.',
    'account.title': 'Account',
    'account.profile': 'Profile',
    'account.language': 'Language',
    'account.notifications': 'Notifications',
    'account.privacy': 'Privacy',
    'account.help': 'Help & Support',
    'account.settings': 'Settings',
    'account.logout': 'Logout',
    'account.level': 'Level',
    'account.points': 'Points',
    'account.name': 'Name',
    'account.phone': 'Phone',
    'account.upgrade': 'Upgrade Account',
    'language.choose': 'Choose Language',
    'language.current': 'Current language',
    'language.changed': 'Language Changed',
    'language.nowIn': 'App is now in',
    'language.cancel': 'Cancel',
    'notifications.title': 'Notifications',
    'notifications.manage': 'Manage your notification preferences',
    'notifications.enableAll': 'Enable All',
    'notifications.disableAll': 'Disable All',
    'notifications.customize': 'Customize',
    'notifications.enabled': 'Notifications Enabled',
    'notifications.disabled': 'Notifications Disabled',
    'notifications.willReceive': 'You will receive all notifications',
    'notifications.wontReceive': 'You will no longer receive notifications',
    'privacy.title': 'Privacy & Security',
    'privacy.protected': 'Your personal data is protected according to our privacy policy.\n\n• Encrypted data\n• No sharing with third parties\n• GDPR compliant',
    'privacy.readPolicy': 'Read Full Policy',
    'privacy.deleteData': 'Delete My Data',
    'privacy.confirmDelete': 'Are you sure? This action is irreversible.',
    'privacy.close': 'Close',
    'help.title': 'Help & Support',
    'help.how': 'How can we help you?',
    'help.faq': 'Frequently Asked Questions',
    'help.contact': 'Contact Support',
    'help.tour': 'Guided Tour',
    'help.whatsapp': 'WhatsApp Customer Service',
    'settings.title': 'Settings',
    'settings.configure': 'Configure your application',
    'settings.theme': 'Theme (Light/Dark)',
    'settings.sounds': 'Sounds and Vibrations',
    'settings.storage': 'Storage',
    'settings.location': 'Location',
    'logout.title': 'Logout',
    'logout.confirm': 'Are you sure you want to logout?',
    'logout.cancel': 'Cancel',
  },
  fr: {
    'auth.sendCode': 'Envoyer le Code à 4 Chiffres',
    'auth.enterCode': 'Entrez le Code de Vérification à 4 Chiffres',
    'auth.testCode': 'Pour les tests : Utilisez le code 1234',
    'auth.phoneNumber': 'Numéro de Mobile',
    'auth.enterPhone': 'Entrez votre numéro de mobile pour commencer',
    'auth.verifyNumber': 'Vérifiez Votre Numéro',
    'auth.codeSentTo': 'Nous avons envoyé un code à 4 chiffres à',
    'auth.resendCode': 'Renvoyer le code de vérification',
    'auth.verifyCode': 'Vérifier le Code',
    'auth.completeProfile': 'Complétez Votre Profil',
    'auth.firstName': 'Prénom',
    'auth.lastName': 'Nom',
    'auth.welcomeBonus': 'Vous recevrez 50 points comme cadeau de bienvenue !',
    'header.search': 'Rechercher des magasins et produits',
    'nav.home': 'Accueil',
    'nav.stores': 'Magasins',
    'nav.deals': 'Offres',
    'nav.wallet': 'Portefeuille',
    'nav.account': 'Compte',
    'home.promotions': 'Promotions',
    'home.partnerStores': 'Magasins Partenaires',
    'home.earnPoints': 'Gagnez des Points !',
    'home.earnPointsDesc': 'Achetez dans les magasins partenaires et gagnez des points à chaque achat',
    'home.giftCards': 'Cartes Cadeaux',
    'home.premiumOffers': 'Offres Premium',
    'home.geantSelection': 'Meilleure Sélection',
    'home.promotion': 'Promotion Spéciale',
    'home.quantity': 'Quantité',
    'home.giftCardTitle': 'Carte Cadeau',
    'home.giftCardRedeem': 'Échanger la carte cadeau {{amount}} ? Cela déduira des points de votre solde.',
    'home.premiumOfferTitle': 'Offre Premium',
    'home.premiumOfferDesc': '{{title}} - {{points}} points. Voulez-vous échanger cette offre ?',
    'home.specialPromotion': 'Promotion Spéciale',
    'home.specialPromoDesc': '{{title}} - Excellente offre dans notre magasin partenaire !',
    'home.cancel': 'Annuler',
    'home.confirm': 'Confirmer',
    'home.success': 'Succès',
    'home.giftCardRedeemed': 'Carte cadeau échangée !',
    'home.viewDetails': 'Voir les Détails',
    'home.viewStore': 'Voir le Magasin',
    'deals.title': 'Offres',
    'deals.upgradeNow': 'Mettre à Niveau',
    'stores.title': 'Magasins',
    'stores.all': 'Tous',
    'stores.food': 'Alimentation',
    'stores.fashion': 'Mode',
    'stores.highTech': 'High Tech',
    'stores.education': 'Éducation',
    'stores.beauty': 'Beauté',
    'stores.health': 'Santé',
    'stores.searchPlaceholder': 'Rechercher des magasins...',
    'stores.noResults': 'Aucun magasin trouvé',
    'stores.cashback': 'cashback',
    'wallet.title': 'Mon Portefeuille',
    'wallet.availablePoints': 'Points Disponibles',
    'wallet.estimated': 'Estimé',
    'wallet.readMore': 'Lire plus',
    'wallet.earnPointsDesc': 'Gagnez des points à chaque achat dans nos magasins partenaires !',
    'wallet.monthlyLimit': 'Limite Mensuelle de Dépenses',
    'wallet.usedThisMonth': 'Utilisé ce mois-ci',
    'wallet.availableThisMonth': 'Disponible ce mois-ci',
    'wallet.splitPayments': 'Paiements Fractionnés',
    'wallet.splitUpTo': 'Fractionnez vos achats jusqu\'à',
    'wallet.months': 'mois',
    'wallet.scanOrder': 'Scanner Commande',
    'wallet.uploadReceipt': 'Télécharger Reçu',
    'wallet.redeem': 'Échanger',
    'wallet.flouciPay': 'Payer avec Flouci',
    'wallet.recentActivity': 'Activité Récente',
    'wallet.earnedAt': 'Gagné chez',
    'wallet.redeemedAt': 'Échangé chez',
    'wallet.howToEarn': 'Comment Gagner des Points ?',
    'wallet.shopAtStores': 'Achetez dans les magasins partenaires',
    'wallet.referFriends': 'Parrainez des amis',
    'wallet.dailyCheckIn': 'Connexion quotidienne',
    'wallet.mobileSubscription': 'Abonnement mobile',
    'wallet.pointsInfo': 'Informations sur les Points',
    'wallet.pointsValue': '1 point = 0.01 SAR',
    'wallet.pointsDesc': 'Les points peuvent être utilisés pour échanger des cartes cadeaux, des réductions et des offres spéciales dans nos magasins partenaires.',
    'wallet.quickActions': 'Actions Rapides',
    'wallet.available': 'Disponible',
    'wallet.maxSplit': 'Fractionnement Max',
    'wallet.splitNotAvailable': 'Le paiement fractionné n\'est pas disponible pour votre niveau actuel',
    'upgrade.title': 'Améliorer Votre Compte',
    'upgrade.subtitle': 'Choisissez le plan qui correspond à votre style de vie',
    'upgrade.currentPlan': 'Plan Actuel',
    'upgrade.mostPopular': 'Le Plus Populaire',
    'upgrade.basic': 'Basic',
    'upgrade.silver': 'Silver',
    'upgrade.gold': 'Gold',
    'upgrade.free': 'Gratuit',
    'upgrade.month': '/mois',
    'upgrade.selectPlan': 'Sélectionner',
    'upgrade.currentPlanBtn': 'Plan Actuel',
    'upgrade.benefits': 'Avantages',
    'upgrade.basicBenefit1': 'Accès aux offres basiques',
    'upgrade.basicBenefit2': 'Gagnez des points sur les achats',
    'upgrade.basicBenefit3': 'Taux de cashback standard',
    'upgrade.basicBenefit4': 'Roue des récompenses quotidiennes',
    'upgrade.silverBenefit1': 'Tous les avantages Basic',
    'upgrade.silverBenefit2': 'Accès aux offres Premium',
    'upgrade.silverBenefit3': '2x points sur tous les achats',
    'upgrade.silverBenefit4': 'Paiements fractionnés jusqu\'à 6 mois',
    'upgrade.silverBenefit5': 'Support client prioritaire',
    'upgrade.silverBenefit6': 'Limite mensuelle : 7 500 SAR',
    'upgrade.goldBenefit1': 'Tous les avantages Silver',
    'upgrade.goldBenefit2': 'Accès aux offres VIP exclusives',
    'upgrade.goldBenefit3': '3x points sur tous les achats',
    'upgrade.goldBenefit4': 'Paiements fractionnés jusqu\'à 12 mois',
    'upgrade.goldBenefit5': 'Gestionnaire de compte dédié',
    'upgrade.goldBenefit6': 'Limite mensuelle : 15 000 SAR',
    'upgrade.goldBenefit7': 'Accès anticipé aux nouvelles fonctionnalités',
    'upgrade.goldBenefit8': 'Bonus anniversaire : 500 points',
    'upgrade.compareTitle': 'Comparer les Plans',
    'upgrade.feature': 'Fonctionnalité',
    'upgrade.dealsAccess': 'Accès aux Offres',
    'upgrade.pointsMultiplier': 'Multiplicateur de Points',
    'upgrade.splitPayment': 'Paiement Fractionné',
    'upgrade.monthlyLimit': 'Limite Mensuelle',
    'upgrade.support': 'Support',
    'upgrade.basicDeals': 'Basic',
    'upgrade.premiumDeals': 'Premium',
    'upgrade.vipDeals': 'VIP Exclusif',
    'upgrade.standard': 'Standard',
    'upgrade.priority': 'Prioritaire',
    'upgrade.dedicated': 'Dédié',
    'upgrade.confirmUpgrade': 'Confirmer la Mise à Niveau',
    'upgrade.confirmMessage': 'Passer au plan {{plan}} pour {{price}}/mois ?',
    'upgrade.cancel': 'Annuler',
    'upgrade.confirm': 'Confirmer',
    'upgrade.success': 'Succès !',
    'upgrade.successMessage': 'Votre compte a été mis à niveau vers {{plan}} !',
    'upgrade.error': 'Erreur',
    'upgrade.errorMessage': 'Échec de la mise à niveau. Veuillez réessayer.',
    'account.title': 'Compte',
    'account.profile': 'Profil',
    'account.language': 'Langue',
    'account.notifications': 'Notifications',
    'account.privacy': 'Confidentialité',
    'account.help': 'Aide et Support',
    'account.settings': 'Paramètres',
    'account.logout': 'Se déconnecter',
    'account.level': 'Niveau',
    'account.points': 'Points',
    'account.name': 'Nom',
    'account.phone': 'Téléphone',
    'account.upgrade': 'Améliorer le Compte',
    'language.choose': 'Choisir la langue',
    'language.current': 'Langue actuelle',
    'language.changed': 'Langue changée',
    'language.nowIn': 'L\'application est maintenant en',
    'language.cancel': 'Annuler',
    'notifications.title': 'Notifications',
    'notifications.manage': 'Gérez vos préférences de notification',
    'notifications.enableAll': 'Activer tout',
    'notifications.disableAll': 'Désactiver tout',
    'notifications.customize': 'Personnaliser',
    'notifications.enabled': 'Notifications activées',
    'notifications.disabled': 'Notifications désactivées',
    'notifications.willReceive': 'Vous recevrez toutes les notifications',
    'notifications.wontReceive': 'Vous ne recevrez plus de notifications',
    'privacy.title': 'Confidentialité & Sécurité',
    'privacy.protected': 'Vos données personnelles sont protégées selon notre politique de confidentialité.\n\n• Données cryptées\n• Aucun partage avec des tiers\n• Conformité RGPD',
    'privacy.readPolicy': 'Lire la politique complète',
    'privacy.deleteData': 'Supprimer mes données',
    'privacy.confirmDelete': 'Êtes-vous sûr ? Cette action est irréversible.',
    'privacy.close': 'Fermer',
    'help.title': 'Aide & Support',
    'help.how': 'Comment pouvons-nous vous aider ?',
    'help.faq': 'Questions Fréquentes (FAQ)',
    'help.contact': 'Contacter le Support',
    'help.tour': 'Visite Guidée',
    'help.whatsapp': 'Service Client WhatsApp',
    'settings.title': 'Paramètres',
    'settings.configure': 'Configurez votre application',
    'settings.theme': 'Thème (Clair/Sombre)',
    'settings.sounds': 'Sons et Vibrations',
    'settings.storage': 'Stockage',
    'settings.location': 'Localisation',
    'logout.title': 'Se déconnecter',
    'logout.confirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
    'logout.cancel': 'Annuler',
  },
  ar: {
    'auth.sendCode': 'إرسال رمز من 4 أرقام',
    'auth.enterCode': 'أدخل رمز التحقق المكون من 4 أرقام',
    'auth.testCode': 'للاختبار: استخدم الرمز 1234',
    'auth.phoneNumber': 'رقم الهاتف المحمول',
    'auth.enterPhone': 'أدخل رقم هاتفك المحمول للبدء',
    'auth.verifyNumber': 'تحقق من رقمك',
    'auth.codeSentTo': 'لقد أرسلنا رمزاً مكوناً من 4 أرقام إلى',
    'auth.resendCode': 'إعادة إرسال رمز التحقق',
    'auth.verifyCode': 'تحقق من الرمز',
    'auth.completeProfile': 'أكمل ملفك الشخصي',
    'header.search': 'البحث عن المتاجر والمنتجات',
    'nav.home': 'الرئيسية',
    'nav.stores': 'المتاجر',
    'nav.deals': 'العروض',
    'nav.wallet': 'المحفظة',
    'nav.account': 'الحساب',
    'home.promotions': 'العروض الترويجية',
    'home.partnerStores': 'المتاجر الشريكة',
    'home.earnPoints': 'اكسب النقاط!',
    'home.earnPointsDesc': 'تسوق من المتاجر الشريكة واكسب نقاطاً مع كل عملية شراء',
    'home.giftCards': 'بطاقات الهدايا',
    'home.premiumOffers': 'العروض المميزة',
    'home.geantSelection': 'أفضل الاختيارات',
    'home.promotion': 'عرض خاص',
    'home.quantity': 'الكمية',
    'home.giftCardTitle': 'بطاقة هدية',
    'home.giftCardRedeem': 'استبدال بطاقة هدية {{amount}}؟ سيتم خصم النقاط من رصيدك.',
    'home.premiumOfferTitle': 'عرض مميز',
    'home.premiumOfferDesc': '{{title}} - {{points}} نقطة. هل ترغب في استبدال هذا العرض؟',
    'home.specialPromotion': 'عرض خاص',
    'home.specialPromoDesc': '{{title}} - عرض رائع في متجرنا الشريك!',
    'home.cancel': 'إلغاء',
    'home.confirm': 'تأكيد',
    'home.success': 'نجاح',
    'home.giftCardRedeemed': 'تم استبدال بطاقة الهدية!',
    'home.viewDetails': 'عرض التفاصيل',
    'home.viewStore': 'عرض المتجر',
    'deals.title': 'العروض',
    'deals.upgradeNow': 'ترقية الآن',
    'stores.title': 'المتاجر',
    'stores.all': 'الكل',
    'stores.food': 'طعام',
    'stores.fashion': 'أزياء',
    'stores.highTech': 'تقنية عالية',
    'stores.education': 'تعليم',
    'stores.beauty': 'جمال',
    'stores.health': 'صحة',
    'stores.searchPlaceholder': 'البحث عن المتاجر...',
    'stores.noResults': 'لم يتم العثور على متاجر',
    'stores.cashback': 'استرداد نقدي',
    'wallet.title': 'محفظتي',
    'wallet.availablePoints': 'النقاط المتاحة',
    'wallet.estimated': 'تقديري',
    'wallet.readMore': 'اقرأ المزيد',
    'wallet.earnPointsDesc': 'اكسب نقاطاً مع كل عملية شراء من متاجرنا الشريكة!',
    'wallet.monthlyLimit': 'الحد الشهري للإنفاق',
    'wallet.usedThisMonth': 'مستخدم هذا الشهر',
    'wallet.availableThisMonth': 'متاح هذا الشهر',
    'wallet.splitPayments': 'الدفعات المقسمة',
    'wallet.splitUpTo': 'قسّم مشترياتك حتى',
    'wallet.months': 'شهور',
    'wallet.scanOrder': 'مسح الطلب',
    'wallet.uploadReceipt': 'تحميل الإيصال',
    'wallet.redeem': 'استبدال',
    'wallet.flouciPay': 'الدفع بفلوسي',
    'wallet.recentActivity': 'النشاط الأخير',
    'wallet.earnedAt': 'تم الكسب من',
    'wallet.redeemedAt': 'تم الاستبدال من',
    'wallet.howToEarn': 'كيفية كسب النقاط؟',
    'wallet.shopAtStores': 'تسوق من المتاجر الشريكة',
    'wallet.referFriends': 'إحالة الأصدقاء',
    'wallet.dailyCheckIn': 'تسجيل الدخول اليومي',
    'wallet.mobileSubscription': 'اشتراك الهاتف المحمول',
    'wallet.pointsInfo': 'معلومات النقاط',
    'wallet.pointsValue': '1 نقطة = 0.01 ريال سعودي',
    'wallet.pointsDesc': 'يمكن استخدام النقاط لاستبدال بطاقات الهدايا والخصومات والعروض الخاصة في متاجرنا الشريكة.',
    'wallet.quickActions': 'الإجراءات السريعة',
    'wallet.available': 'متاح',
    'wallet.maxSplit': 'أقصى تقسيم',
    'wallet.splitNotAvailable': 'الدفع المقسم غير متاح لمستواك الحالي',
    'upgrade.title': 'ترقية حسابك',
    'upgrade.subtitle': 'اختر الخطة التي تناسب أسلوب حياتك',
    'upgrade.currentPlan': 'الخطة الحالية',
    'upgrade.mostPopular': 'الأكثر شعبية',
    'upgrade.basic': 'بيسك',
    'upgrade.silver': 'سيلفر',
    'upgrade.gold': 'جولد',
    'upgrade.free': 'مجاني',
    'upgrade.month': '/شهر',
    'upgrade.selectPlan': 'اختيار الخطة',
    'upgrade.currentPlanBtn': 'الخطة الحالية',
    'upgrade.benefits': 'المزايا',
    'upgrade.basicBenefit1': 'الوصول إلى العروض الأساسية',
    'upgrade.basicBenefit2': 'اكسب نقاطاً على المشتريات',
    'upgrade.basicBenefit3': 'معدل استرداد نقدي قياسي',
    'upgrade.basicBenefit4': 'عجلة المكافآت اليومية',
    'upgrade.silverBenefit1': 'جميع مزايا بيسك',
    'upgrade.silverBenefit2': 'الوصول إلى العروض المميزة',
    'upgrade.silverBenefit3': 'ضعف النقاط على جميع المشتريات',
    'upgrade.silverBenefit4': 'الدفع المقسم حتى 6 أشهر',
    'upgrade.silverBenefit5': 'دعم عملاء ذو أولوية',
    'upgrade.silverBenefit6': 'الحد الشهري: 7,500 ريال سعودي',
    'upgrade.goldBenefit1': 'جميع مزايا سيلفر',
    'upgrade.goldBenefit2': 'الوصول إلى العروض الحصرية VIP',
    'upgrade.goldBenefit3': '3x النقاط على جميع المشتريات',
    'upgrade.goldBenefit4': 'الدفع المقسم حتى 12 شهراً',
    'upgrade.goldBenefit5': 'مدير حساب مخصص',
    'upgrade.goldBenefit6': 'الحد الشهري: 15,000 ريال سعودي',
    'upgrade.goldBenefit7': 'الوصول المبكر للميزات الجديدة',
    'upgrade.goldBenefit8': 'مكافأة عيد ميلاد: 500 نقطة',
    'upgrade.compareTitle': 'مقارنة الخطط',
    'upgrade.feature': 'الميزة',
    'upgrade.dealsAccess': 'الوصول للعروض',
    'upgrade.pointsMultiplier': 'مضاعف النقاط',
    'upgrade.splitPayment': 'الدفع المقسم',
    'upgrade.monthlyLimit': 'الحد الشهري',
    'upgrade.support': 'الدعم',
    'upgrade.basicDeals': 'أساسي',
    'upgrade.premiumDeals': 'مميز',
    'upgrade.vipDeals': 'حصري VIP',
    'upgrade.standard': 'قياسي',
    'upgrade.priority': 'ذو أولوية',
    'upgrade.dedicated': 'مخصص',
    'upgrade.confirmUpgrade': 'تأكيد الترقية',
    'upgrade.confirmMessage': 'الترقية إلى خطة {{plan}} مقابل {{price}}/شهر؟',
    'upgrade.cancel': 'إلغاء',
    'upgrade.confirm': 'تأكيد',
    'upgrade.success': 'نجاح!',
    'upgrade.successMessage': 'تمت ترقية حسابك إلى {{plan}}!',
    'upgrade.error': 'خطأ',
    'upgrade.errorMessage': 'فشل في ترقية الحساب. يرجى المحاولة مرة أخرى.',
    'account.title': 'الحساب',
    'account.profile': 'الملف الشخصي',
    'account.language': 'اللغة',
    'account.notifications': 'الإشعارات',
    'account.privacy': 'الخصوصية',
    'account.help': 'المساعدة والدعم',
    'account.settings': 'الإعدادات',
    'account.logout': 'تسجيل الخروج',
    'account.level': 'المستوى',
    'account.points': 'النقاط',
    'account.name': 'الاسم',
    'account.phone': 'الهاتف',
    'account.upgrade': 'ترقية الحساب',
    'language.choose': 'اختر اللغة',
    'language.current': 'اللغة الحالية',
    'language.changed': 'تم تغيير اللغة',
    'language.nowIn': 'التطبيق الآن',
    'language.cancel': 'إلغاء',
    'notifications.title': 'الإشعارات',
    'notifications.manage': 'إدارة تفضيلات الإشعارات',
    'notifications.enableAll': 'تفعيل الكل',
    'notifications.disableAll': 'تعطيل الكل',
    'notifications.customize': 'تخصيص',
    'notifications.enabled': 'تم تفعيل الإشعارات',
    'notifications.disabled': 'تم تعطيل الإشعارات',
    'notifications.willReceive': 'ستتلقى جميع الإشعارات',
    'notifications.wontReceive': 'لن تتلقى الإشعارات بعد الآن',
    'privacy.title': 'الخصوصية والأمان',
    'privacy.protected': 'بياناتك الشخصية محمية وفقًا لسياسة الخصوصية.\n\n• بيانات مشفرة\n• لا مشاركة مع أطراف ثالثة\n• متوافق مع GDPR',
    'privacy.readPolicy': 'اقرأ السياسة الكاملة',
    'privacy.deleteData': 'حذف بياناتي',
    'privacy.confirmDelete': 'هل أنت متأكد؟ هذا الإجراء لا رجعة فيه.',
    'privacy.close': 'إغلاق',
    'help.title': 'المساعدة والدعم',
    'help.how': 'كيف يمكننا مساعدتك؟',
    'help.faq': 'الأسئلة الشائعة',
    'help.contact': 'اتصل بالدعم',
    'help.tour': 'جولة إرشادية',
    'help.whatsapp': 'خدمة عملاء واتساب',
    'settings.title': 'الإعدادات',
    'settings.configure': 'قم بتكوين تطبيقك',
    'settings.theme': 'السمة (فاتح/داكن)',
    'settings.sounds': 'الأصوات والاهتزازات',
    'settings.storage': 'التخزين',
    'settings.location': 'الموقع',
    'logout.title': 'تسجيل الخروج',
    'logout.confirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    'logout.cancel': 'إلغاء',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('fr');
  const [isLoading, setIsLoading] = useState(true);

  // Load saved language on mount
  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const savedLanguage = await AsyncStorage.getItem('app_language');
      if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'fr' || savedLanguage === 'ar')) {
        setLanguage(savedLanguage as Language);
        console.log('Loaded language:', savedLanguage);
      }
    } catch (error) {
      console.error('Error loading language:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const changeLanguage = async (newLanguage: Language) => {
    try {
      console.log('Changing language to:', newLanguage);
      setLanguage(newLanguage);
      await AsyncStorage.setItem('app_language', newLanguage);
      console.log('Language saved:', newLanguage);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  const t = (key: string): string => {
    return (translations as any)[language][key] || key;
  };

  React.useEffect(() => {
    if (language === 'ar') {
      try {
        I18nManager.allowRTL(true);
      } catch {}
    } else {
      try {
        I18nManager.allowRTL(false);
      } catch {}
    }
  }, [language]);

  if (isLoading) {
    return null;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      <>{children}</>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
